services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=${CONNECTION_STRING_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SoldierTrackDb;User Id=sa;Password=${CONNECTION_STRING_PASSWORD};TrustServerCertificate=True;
      - SmtpSettings__Host=${SMTP_HOST}
      - SmtpSettings__Port=${SMTP_PORT}
      - SmtpSettings__Username=${SMTP_USERNAME}
      - SmtpSettings__Password=${SMTP_PASSWORD}
      - AdminSettings__Email=${ADMIN_EMAIL}
      - AdminSettings__Password=${ADMIN_PASSWORD}
    entrypoint:
      - /wait-for-it.sh
      - sqlserver
      - "1433"
      - --
      - dotnet
      - SoldierTrack.Web.dll

volumes:
  sqlserverdata:
