global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'soldiertrack_web'
    metrics_path: /metrics
    static_configs:
      - targets: ['web:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
