{
 "title": "ASP.NET Core Metrics",
 "tags": [
  "aspnetcore",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Requests Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "reqs/sec"
    }
   ]
  },
  {
   "title": "P95 Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95(ms)"
    }
   ]
  },
  {
   "title": "Private Memory (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "process_private_memory_bytes", "legendFormat": "bytes" }
   ]
  }
 ]
}